server:
  port: 8088
spring:
  application:
    # 应用名称，可选，默认也是工程名
    name: emovie
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库的各个信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.143.247.127:3306/emovie?characterEncoding=utf-8&userSSL=false
    username: root
#    password: root
    password: xjBn+WSkT_1~+E#GtVG6spvKv#evdP1e

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 设置MyBatis-Plus的全局配置
#  global-config:
#    db-config:

  # 配置类型别名所对应的包
  type-aliases-package: com.lqyrmk.emovie.entity
  # 配置映射文件路径
  mapper-locations: classpath:mybatis/mapper/*.xml
